### ISSUE TITLE
Convert underscores in package name to CamelCase modules

### ISSUE THREAD

**Issue by rmarable-iseatz** [mozy/ruby-protocol-buffers#8]
I would expect underscored package names like this:

package big_system;

to compile to this:

module BigSystem
  ...
end

Currently it produces:

module Big_system

and Ruby gives: uninitialized constant Object::BigSystem

**Comment by codekitchen** [comment]
I would prefer not to munge the package name at all, to match the behavior of the C++ and Java protobuf compilers, but since we have to capitalize it anyway to make it a valid ruby module name, i could certainly buy the argument that we should go all the way and just follow the convention that libraries like rails have established. So yeah, +1 from me.
